experiment to run ga on mac-14

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,7 +20,9 @@ jobs:
     name: TEST WITH PYTHON ${{ matrix.python_version }}
 
     # The type of runner that the job will run on
-    runs-on: ubuntu-22.04
+    # experimental # runs-on: ubuntu-22.04
+    runs-on: macos-14
+    # experimental end
     strategy:
       matrix:
         python_version: ['3.9', '3.10', '3.11']
@@ -41,6 +43,17 @@ jobs:
         run: |
           poetry install
           poetry run flake8 submitr
+          echo "Installing docker."
+          HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
+          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+          open -a /Applications/Docker.app --args --unattended --accept-license
+          echo "Starting docker."
+          echo "Waiting for docker to be up and running. This can take over 2 minutes ..."
+          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
+          echo "Docker now seems to be up/running."
+          echo "Building Linux binaries."
+          make exe-linux
+          echo "Done building Linux binaries."
       
       - name: CI
         run: |
