experiment to run ga on mac-14

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,22 +44,17 @@ jobs:
           poetry install
           poetry run flake8 submitr
           echo "Installing docker."
-          brew install docker
-          echo "Installed docker."
+          HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
+          echo "Preparing docker."
+          sudo /Applications/Docker.app/Contents/MacOS/Docker\ Desktop.app/Contents/MacOS/Docker\ Desktop --unattended --install-privileged-components
           echo "Starting docker."
-          colima start
-          echo "Started docker."
-          # HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
-          # sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
-          # open -a /Applications/Docker.app --args --unattended --accept-license
-          # echo "Starting docker."
-          # open -a /Applications/Docker.app --unattended --install-privileged-components
-          # echo "Waiting for docker to be up and running. This can take over 2 minutes ..."
-          # while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
-          # echo "Docker now seems to be up/running."
-          # echo "Building Linux binaries."
-          # make exe-linux
-          # echo "Done building Linux binaries."
+          open -a /Applications/Docker.app --args --unattended --accept-license
+          echo "Waiting for docker get up/running. This can take over 2 minutes ..."
+          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
+          echo "Docker now seems to be up/running."
+          echo "Building Linux binaries."
+          make exe-linux
+          echo "Done building Linux binaries."
       
       - name: CI
         run: |
